#ifndef PROJET_ABSTRACTUI_HPP
#define PROJET_ABSTRACTUI_HPP


class AbstractUI {
public:
    // NE PAS ENLEVER. FONDAMENTAL POUR ASSURER LA DESTRUCTION CORRECTE DES OBJETS;
    virtual ~AbstractUI() = default;
};


#endif //PROJET_ABSTRACTUI_HPP
